### ISSUE TITLE
REF_TABLE_PATH file missing

### ISSUE THREAD

**Issue by gpcr** [yiminghu/post-GWAS-pipeline#1]
I am trying to install the pipeline:  Where can I find this file: 

REF_TABLE_PATH=/gpfs/ysm/pi/zhao/from_louise/yh367/VA/workflow/GNOVA/sumstats/match_table_full.csv

thanks

**Comment by frankji** [comment]
You need to create the table with these columns 
"X","Categ","Trait","Curated_file","Code"
Namely index, category(source), trait name, file path, unique code for the trait
You may download these summary stats with the info from UKBiobank or LDHUB.
Hope this helps.

**Comment by gpcr** [comment]
Thank you, @frankji
